/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	Set_RCC();
	SET_BIT(GPIOA->MODER, GPIO_MODER_MODER8_1);
	CLEAR_BIT(GPIOA->OTYPER, GPIO_OTYPER_OT8);
	CLEAR_BIT(GPIOA->PUPDR, GPIO_PUPDR_PUPD8);
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEEDR8_0, GPIO_OSPEEDER_OSPEEDR8_1);
	CLEAR_BIT(GPIOA->AFR[1], GPIO_AFRH_AFSEL8);




	while(1)
	{

	}
}
