/*
 * RCC.c
 *
 *  Created on: 23 січ. 2023 р.
 *      Author: mrem
 */
#include "RCC.h"

void Set_HSE(void)
{
	SET_BIT(RCC->CR, RCC_CR_HSEON);
	while(!(RCC->CR & RCC_CR_HSERDY));	// Wait when HSE is been ready
}

void Set_FLASH_Latency(void)
{
	// Set FLASH latency
	SET_BIT(FLASH->ACR, FLASH_ACR_LATENCY_2WS);
	while((FLASH->ACR & FLASH_ACR_LATENCY) != FLASH_ACR_LATENCY_2WS);	// Wait when FLASH_LATENCY is been ready
}

void Set_PLL()
{
	MODIFY_REG(RCC->PLLCFGR, RCC_PLLCFGR_PLLSRC | RCC_PLLCFGR_PLLM | RCC_PLLCFGR_PLLN | RCC_PLLCFGR_PLLP, RCC_PLLCFGR_PLLSRC_HSE | 20 << RCC_PLLCFGR_PLLM_Pos | 120 << RCC_PLLCFGR_PLLN_Pos | RCC_PLLCFGR_PLLP_1);
	//CLEAR_BIT(RCC->PLLCFGR, RCC_PLLCFGR_PLLP_0);
	SET_BIT(RCC->CR, RCC_CR_PLLON);
	while(READ_BIT(RCC->CR, RCC_CR_PLLRDY) == (RCC_CR_PLLRDY));	// Wait when PLL is been ready
}

void Set_RCC(void)
{
	Set_FLASH_Latency();
	SET_BIT(PWR->CR, PWR_CR_VOS_1);
	// On HSE
	Set_HSE();
	Set_PLL();
	MODIFY_REG(RCC->CFGR, RCC_CFGR_HPRE, RCC_CFGR_HPRE_DIV1);

	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1, RCC_CFGR_PPRE1_DIV2);
	MODIFY_REG(RCC->CFGR, RCC_CFGR_PPRE1, RCC_CFGR_PPRE1_DIV1);

	MODIFY_REG(RCC->CFGR, RCC_CFGR_SW, RCC_CFGR_SW_PLL);

	SET_BIT(RCC->CFGR, RCC_CFGR_MCO1_0 | RCC_CFGR_MCO1_1 | RCC_CFGR_MCO1PRE_0 | RCC_CFGR_MCO1PRE_1 | RCC_CFGR_MCO1PRE_2);
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);



}
